### ISSUE TITLE
why is this Yanked on crates.io?

### ISSUE THREAD

**Issue by SET001** [Kromey/fast_poisson#38]
Hi. Why is this crate marked as yanked on crates.io? Does it mean you going to stop developing/supporting it? I just used it in my plugin and was a bit disappointed seeing it is yanked.

**Comment by Kromey** [comment]
The crate is not yanked; version 1.0.1 is yanked, leaving [1.0.0 as the current version](https://crates.io/crates/fast_poisson). I'm happy you're using it and have every intention to continue supporting it, especially as I use it myself in a few of my own projects!

Basically, 1.0.1 was a well-intentioned but uninformed attempt to work around what I perceived to be a violation of SemVer in a dependency of a dependency - specifically, the `half` crate bumped their MSRV to higher than this crate's, but did so on a minor revision (2.3.0) rather than a major revision. After discussion with other members of the Rust community, however, I came to realize that it's not this crate's responsibility to enforce MSRV in dependencies, and instead if dependent crates need that lower Rust version for any reason it's contingent on them to pin a compatible version in cases like this - fortunately easily done with e.g. `cargo update -p half@2.3.1 --precise 2.2.1`. I therefore reverted that version. At present, you should be using version 1.0.0.

I've also previously yanked version 0.5.1, as in that version I bumped the Rust edition to 2021, which of course is not compatible with the crate's MSRV of Rust 1.51.0; as the edition bump provides no significant advantages, I decided reverting that was preferable to bumping the MSRV.

**Comment by SET001** [comment]
Oh, sorry for this misunderstanding. I'm so happy you continue working on it )
